### ISSUE TITLE
Give Steve permission to access settings for NextScripts: Social Networks Auto-Poster

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_STCATH#11]
Installed and activated the plug-in however, I apparently do no have significant permission to edit the settings.

![](https://ibin.co/3thZHjfc6qlQ.png)

**Comment by BigActual** [comment]
Uninstalling.

**Comment by d4mation** [comment]
I never saw this one either. Weird. Looks like it was the same day.

**Comment by BigActual** [comment]
meh nbd.
