### ISSUE TITLE
Add external link capability to Features

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_STCATH#6]
There is already an internal link built into Features. Please add the ability to link off site.

**Comment by BigActual** [comment]
@joelworsham Can we knock this one out today before I call the client about #5 ?

**Comment by BigActual** [comment]
@joelworsham I see this is complete already. Please close this issue if you're satisfied. I'll let the client know we're ready. Thanks.

**Comment by joelworsham** [comment]
Issue will be closed one both issues are complete and I version the release.
