### ISSUE TITLE
Recurrence fields not populating 

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_STCATH#8]
When a new event is labelled as recurring, a series of additional fields should become available including, ...and will end [On, after, never ▾], [end date], and Recurrence Description: [Text]

This does not occur for either the user Jerry McCarty or I. I replicated the issue on my machine.

**Comment by brashrebel** [comment]
We can do this by 7/16. There's a weird little javascript bug that is elusive.

**Comment by BigActual** [comment]
Client is asking about the status of this. Where are we on completion?

**Comment by d4mation** [comment]
All set!

![image](https://cloud.githubusercontent.com/assets/7770631/17212371/cfaba2fe-549c-11e6-98c2-099bc26f1ce4.png)

**Comment by BigActual** [comment]
Per @joelworsham 's note in Slack, "Do you know if recurrence should indeed create a new event for every recurring date? In my mind, you should be able to create an event, set to recurring, and manage it from ONE post... but it seems that there’s a NEW post for every single recurring date, which is so obnoxious"

I agree that it is obnoxious and seems counter intuitive. Eric, is this the expected output? Is there a way to improve the situation?

**Comment by d4mation** [comment]
Looking at the documentation, it seems that creating a new "Event" for each one is expected behavior:

> Since every event has a corresponding entry in the database, a never ending event would potentially mean that an infinite number of **database entries [Events]** would have to be generated – which is clearly unworkable: the last thing we want is to blow up your database! Similarly, a long-term recurrence patterns with hundreds of instances could slow things down.

This is primarily so that if schedules for a recurring event were to change, you could tell it to "Edit Upcoming" to change only future Events of that Recurrence. You could also Edit a specific one if for one day that week, things need to be rescheduled.

It does make things look a little cluttered, but it is meant for flexibility in use cases.

> **Breaking off a Single Event**
> 
> When you are viewing an instance of an event on your site, if you have the Admin Toolbar enabled you should see an “Edit Event” link in the toolbar. Upon hovering over this link, a drop down menu should appear with a few options, one of which is “Break from Series.”
> 
> **Breaking off a Batch of Events**
> 
> The above method covers breaking off one, singular event from the larger series. This second method doesn’t break off just one event—it essentially splits the main recurring series in two, leaving two separate recurrence series.
> 
> To do this, go to the “Events” page in your site’s wp-admin and locate event at which you want to split up the series. Hover over the title of this event, and look for the “Edit Upcoming” link. Click the link, click “confirm” when prompted to, and the series will be split at this event.
> 
> When is this “Edit Upcoming” link useful? Well, say you have an event that runs for a whole year. It happens every Friday at 7pm. Then about four months into the year, things change and the event gets shifted back to 8pm every Friday. If the change is going into effect on April 1st, for example then you could go to the April 1st event and use the “Edit Upcoming” feature to make this event and every event after it start at 8pm instead of 7pm.
